#!/bin/bash
checkdup_process()
{
#TIME_ALARM=3600 ## threshold count in 3600 sec
SCRIPT_NAME=${1}
PARENT_PID=${2}
CURRENT_PROCESS_ID=$(echo $(ps --ppid ${PARENT_PID} |grep -v "PID" |awk '{print $1}') |sed 's/ //g')
CURRENT_PROCESS_ID=$(echo "${CURRENT_PROCESS_ID}" |sed s/\|$//g)
SCRIPT_NUMBER=$(ps -ef |grep "${SCRIPT_NAME}" |grep -v "grep" |egrep -v "${PARENT_PID}|${CURRENT_PROCESS_ID}" |wc -l)
NORMAL=$(echo "${DUPTHRESHOLD}"|awk -F: '{print $1}')
ALARM=$(echo "${DUPTHRESHOLD}"|awk -F: '{print $2}')
HISTORY_PS_RUNNING=${LOG_PATH}/checkdup_running_$(date +%Y%m%d).pid
if [ ${SCRIPT_NUMBER} -gt ${NORMAL} ]
   then
        SCRIPT_NAME=$(echo ${SCRIPT_NAME}|awk -F"/" '{print $NF}')
	WRITE_LOG "${SCRIPT_NAME} PID:${PARENT_PID} Over threshold is duplicate running,cpu -> $(sar 1 1 |grep "Average" | awk '{print "%iowait="$6 "," " %idle="$NF}')"
        echo "$(date +%H:%M:%S) ${SCRIPT_NAME}:${PARENT_PID}" >> ${HISTORY_PS_RUNNING}
        COUNT=$(grep "${SCRIPT_NAME}" ${HISTORY_PS_RUNNING} |tail -$(expr ${ALARM} + 1 ) |wc -l)
        TIME1=$(grep "${SCRIPT_NAME}" ${HISTORY_PS_RUNNING} | tail -$(expr ${ALARM} + 1 )|head -1 |awk '{print $1}')
        SEC1=$(date +%s -d ${TIME1})
        SEC2=$(date +%s -d $(date +%H:%M:%S))
        DIFFSEC=$(expr ${SEC2} - ${SEC1})
        if [ ${COUNT} -gt ${ALARM} ] && [ ${DIFFSEC} -lt ${TIMEDUP_ALARM} ]
          then 
        	echo "ERROR ${SCRIPT_NAME} PID:${PARENT_PID} Over threshold is duplicate running $(basename $0),cpu -> $(sar 1 1 |grep "Average" | awk '{print "%iowait="$6 "," " %idle="$NF}')" 
                WRITE_ALARM "${SCRIPT_NAME}-duplicate" "MAJOR" "${SCRIPT_NAME} duplicate running"
                 
         exit 3
        fi
 exit 4
fi
}

